provider: openstack
env:
  OS_AUTH_URL: "https://auth.cloud.ovh.net/v2.0/"
  OS_IDENTITY_API_VERSION: 2
  OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
  OS_REGION_NAME: UK1
  OS_TENANT_ID: "9d596a0506974e0f8c79673edf0bbdd3"
  OS_TENANT_NAME: "9616699805113213"
  OS_USERNAME: "jrGMbHHjkUQ7"
