provider: datadog
major-version: 4
lint: false
makeTemplate: bridged
team: ecosystem
env:
  DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
  DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
javaGenVersion: v0.9.3
